### ISSUE TITLE
Find a gallery for the art works

### ISSUE THREAD

**Issue by urecio** [urecio/axelilla#3]

**Comment by axelilla** [comment]
http://www.jssor.com/skins/thumbnail-navigator-05.html

http://www.jssor.com/demos/nearby-image-partial-visible-slider.html

**Comment by axelilla** [comment]
Done? well done, can I see it?

**Comment by urecio** [comment]
It's been closed because we decided to get rid of the gallery, didn't we? Please, reopen it if we will also do the gallery ;)
